---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: install java
    apt:
     name: openjdk-17-jre
     state: present

  - name: install maven
    get_url:
     url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
     dest: /opt

  - name: extract maven package
    unarchive:
     src: /opt/apache-maven-3.9.9-bin.tar.gz
     dest: /opt
     remote_src: yes